services:
  java:
    container_name: ${COMPOSE_PROJECT_NAME}_java
    image: attendance-java
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    env_file:
      - ./../.env
    restart: unless-stopped
    command: java -Djava.security.egd=file:/dev/./urandom -jar /project/attendance-0.0.1-SNAPSHOT.jar

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: unless-stopped
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432